[book]
title = "Введение в теорию графов"
authors = ["Eva"]
language = "ru"
src = "src"
description = "Онлайн-конспект лекций"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = false

[preprocessor.katex]


